import { Cpu, Terminal } from "lucide-react";

function AISummary({ aiSummary }) {
  return (
    <div className="glass rounded-[24px] p-8 border border-cyan-500/15 animate-fade-in-up">

      {/* HEADER */}
      <div className="flex items-center gap-3 mb-6">
        <div className="w-10 h-10 rounded-xl bg-cyan-500/15 flex items-center justify-center">
          <Cpu className="text-cyan-400" size={22} />
        </div>
        <div>
          <h2 className="text-xl font-black text-white">AI Vehicle Summary</h2>
          <p className="text-gray-500 text-xs">Generated by inspection engine</p>
        </div>
      </div>

      {/* TERMINAL STYLE CONTENT */}
      <div className="bg-black/50 rounded-2xl p-6 border border-white/5">
        <div className="flex items-center gap-2 mb-4 pb-3 border-b border-white/10">
          <div className="w-3 h-3 rounded-full bg-red-500" />
          <div className="w-3 h-3 rounded-full bg-yellow-500" />
          <div className="w-3 h-3 rounded-full bg-green-500" />
          <span className="text-gray-600 text-xs ml-2 flex items-center gap-1">
            <Terminal size={11} /> report.ai
          </span>
        </div>
        <pre className="text-gray-300 text-sm leading-loose whitespace-pre-wrap font-mono">
          {aiSummary}
        </pre>
      </div>

    </div>
  );
}

export default AISummary;